# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 20:03:25 2026

@author: Jules
"""


import matplotlib.pyplot as plt
import numpy as np
import sympy as sm
import sympy.physics.mechanics as me
from opty import Problem
from opty.utils import parse_free
from generate_eom_model_level_1 import generate_model
from utils import plot_optimal_solution, animate_solution, save_results, export_results_as_csv, stats_plot_about_same_model
from utils import make_new_results_folder
import matplotlib.pyplot as plt
import time
from scipy.interpolate import interp1d


class SOCP_problem:
    
    def __init__(self, NUM_MODELS, model_type):
        """
        Initialize the SOCP_problem class that can handle the optimization 
        process using Opty for different model type. The problem is solving for
        optimal control for multiple episodes at the same time. Gaussian noise 
        is introduced in each model.

        Parameters
        ----------
        NUM_MODELS : int
            Nomber of models to optimize at the same time 
            (ie. number of episodes).
        model_type : str
            type of model (i.e. name of model generated by the 'generate_model'
            function).

        Returns
        -------
        None.

        """
        
        
        # Generates N models and compile them
        time_0 = time.time()
        model_names = [f'm{k}' for k in range(NUM_MODELS)]
        
        print(f'PROBLEM INITIALIZED - {NUM_MODELS} models of type "{model_type}":')

        t_list, x_list, r_dep_list, r_ind_list, k_list ,eoms_list, p_list, bicycle_list, disturbance_list, W_list = [], [], [],[],[],[],[],[],[], []

        for model in model_names:
            t_model, x_model, r_dep_model, r_ind_model, k_model, eoms_model, p_model, bicycle_model, disturbance_model, W_model = generate_model(model)
            
            t_list.append(t_model)
            x_list.append(x_model)
            r_dep_list.append(r_dep_model)
            r_ind_list.append(r_ind_model)
            k_list.append(k_model)

            eoms_list.append(eoms_model)
            p_list.append(p_model)
            bicycle_list.append(bicycle_model)
            disturbance_list.append(disturbance_model)
            W_list.append(W_model)

        self.NUM_MODELS = NUM_MODELS
        self.t = t_list[0]
        
        
        #dependant input (from feedback) are treated as state variables
        #They are include once in the x vector beacause they are common to all models
        
        self.x = x_list[0].col_join(r_dep_list[0])
        self.r = r_ind_list[0]
        self.k = k_list[0]

        self.eoms = eoms_list[0]
        self.p = p_list[0]
        self.disturbance = disturbance_list[0]
        self.W = W_list[0]

        self.bicycle_list = bicycle_list
        
        self.x_list = x_list
        self.r_ind_list = [r_ind_list[0]]
        self.r_dep_list = [r_dep_list[0]]


        self.disturbance_list = disturbance_list
        
        self.W_list  = W_list
        
        if self.NUM_MODELS > 1:
            
            self.x = x_list[0]
            
            for k in range(1, NUM_MODELS):
                self.x = self.x.col_join(x_list[k])
                # self.r = self.r.col_join(r_list[k])
                self.eoms = self.eoms.col_join(eoms_list[k])
                self.disturbance = self.disturbance.col_join(disturbance_list[k])
                self.W = self.W.col_join(W_list[k])

            self.x = self.x.col_join(r_dep_list[0])

        

        self.param, self.param_vals = zip(*self.p.items())

        self.NUM_STATES = len(x_list[0]) + len(r_dep_list[0]) #States include the dep torques 
        self.NUM_INPUTS = len(r_ind_list[0]) 
        self.NUM_KNOWN_TRAJ = 1
        self.NUM_GAINS = len(self.k)
        
        self.NUM_STATES_TOT = self.NUM_MODELS*len(x_list[0]) + len(r_dep_list[0]) #States include the dep torques 
        # self.NUM_INPUTS = NUM_MODELS*self.NUM_INPUTS
        time_1 = time.time()
        
        self.init_time = round(time_1 - time_0, 2)
        
        self.model_type = model_type

        
        print(f'-MODEL(S) INITIALIZED - { self.init_time} sec')
        


    def generate_bounds_and_contstraints(self, SPEED, SAMPLING_FREQUENCY):
        """
        Defines the bounds and the constraints of the optimal problem.
        Values are used by default, but new ones can be defined by over writing
        resulting dictionaries.

        Parameters
        ----------
        SPEED : float
            Longitudinal speed of the bicycle.
        SAMPLING_FREQUENCY : int
            number of nodes per unit of simulated time

        Returns
        -------
        None.

        """
        
        self.bounds = {}
        self.initial_state_constraints = {}
        self.final_state_constraints = {}
        self.SPEED = SPEED
        
        self.WEIGHT = 0.5
        self.DURATION = 3
        self.SAMPLING_FREQUENCY = SAMPLING_FREQUENCY
        self.NUM_NODES = self.SAMPLING_FREQUENCY*self.DURATION #Au moins 10 Hz
        self.INTERVAL_VALUE = self.DURATION / (self.NUM_NODES - 1)
        
        steer_torque, roll_torque = self.x[-2:]
        # K_steer, K_roll = self.k
        
        # K_s_q4, K_s_q7, K_s_u4, K_s_u7, K_r_q4, K_r_q7, K_r_u4, K_r_u7 = self.k
        
        # print(self.r)
        
        pedaling_torque = self.r[0]
        
        self.bounds[steer_torque] = (-30, 30) #ok
        self.bounds[roll_torque] = (-100, 100)
        self.bounds[pedaling_torque] = (-65, 0)
        
        
        # self.bounds[K_steer] = (-10, 10)
        # self.bounds[K_roll] = (-10, 10)
        self.initial_state_constraints[steer_torque] = 0
        self.initial_state_constraints[pedaling_torque] = 0
        
        for gain in self.k:
            self.bounds[gain] = (-300, 300)

        
        for model_index in range(self.NUM_MODELS):
            print('model_index:', model_index)
            
            
            # print(self.x[:-len(self.r_dep_list[0])][model_index*(self.NUM_STATES - len(self.r_dep_list[0])):(self.NUM_STATES - len(self.r_dep_list[0]))*model_index + (self.NUM_STATES - len(self.r_dep_list[0]))//2])
            # print(self.x[:-len(self.r_dep_list[0])][model_index*self.NUM_STATES + self.NUM_STATES//2:model_index*self.NUM_STATES + self.NUM_STATES])

            # print(self.x[:-len(self.r_dep_list[0])])

            q1, q2, q3, q4, q5, q6, q7, q8 = self.x[:-len(self.r_dep_list[0])][model_index*(self.NUM_STATES - len(self.r_dep_list[0])):(self.NUM_STATES - len(self.r_dep_list[0]))*model_index + (self.NUM_STATES - len(self.r_dep_list[0]))//2]
            u1, u2, u3, u4, u5, u6, u7, u8 = self.x[:-len(self.r_dep_list[0])][model_index*(self.NUM_STATES - len(self.r_dep_list[0])) + (self.NUM_STATES - len(self.r_dep_list[0]))//2:model_index*(self.NUM_STATES - len(self.r_dep_list[0])) + (self.NUM_STATES - len(self.r_dep_list[0]))]
            # steer_torque, pedaling_torque = self.r[model_index*self.NUM_INPUTS:self.NUM_INPUTS*(model_index+1)]

    
            self.bounds[q1] = (-0.1, self.SPEED*self.DURATION*1.1)
            self.bounds[q2] = (-2, 2) #Si large la vélo est stabilisé mais part sur le coté
            self.bounds[q3] = (-0.6, 0.6)
            self.bounds[q4] = (-0.6, 0.6)
            self.bounds[q5] = (-1, 1)
            self.bounds[q6] = (-100, 0)
            self.bounds[q7] = (-0.6, 0.6)
            self.bounds[q8] = (-100, 0)
            self.bounds[u1] = (self.SPEED*0.95, self.SPEED*1.05) #ok
            self.bounds[u2] = (-5, 5) #ok
            self.bounds[u3] = (-2.0, 2.0)
            self.bounds[u4] = (-4.0, 4.0)
            self.bounds[u5] = (-4.0, 4.0)
            self.bounds[u6] = (-20.0, 0.0)
            self.bounds[u7] = (-4.0, 4.0) #ok
            self.bounds[u8] = (-20.0, 0.0)

    
    
    
            self.initial_state_constraints[q1] = 0.0
            self.initial_state_constraints[q2] = 0.0
            self.initial_state_constraints[q3] = 0.0
            # self.initial_state_constraints[q4] = 0.0
            self.initial_state_constraints[q5] = 0.39968039870670147 # Super critique
            self.initial_state_constraints[q6] = 0.0
            self.initial_state_constraints[q7] = 0.0
            self.initial_state_constraints[q8] = 0.0
            self.initial_state_constraints[u1] = self.SPEED
            self.initial_state_constraints[u2] = 0.0
            self.initial_state_constraints[u3] = 0.0
            self.initial_state_constraints[u4] = 0.0
            self.initial_state_constraints[u5] = 0.0
            self.initial_state_constraints[u6] = - self.SPEED/self.param_vals[-6]
            self.initial_state_constraints[u7] = 0.0
            self.initial_state_constraints[u8] = - self.SPEED/self.param_vals[-2]
            

        
    
    
            # self.final_state_constraints[q1] = self.SPEED*self.DURATION
            # self.final_state_constraints[q2] = 0.0
            # self.final_state_constraints[q3] = 0.0
            # self.final_state_constraints[q4] = 0.0
            # self.final_state_constraints[q5] = -0.314
            # self.final_state_constraints[q6] = 0.0
            # self.final_state_constraints[q7] = 0.0
            # self.final_state_constraints[q8] = 0.0
            # self.final_state_constraints[u1] = self.SPEED
            # self.final_state_constraints[u2] = 0.0
            # self.final_state_constraints[u3] = 0.0
            self.final_state_constraints[u4] = 0.0
            # self.final_state_constraints[u5] = 0.0
            # self.final_state_constraints[u6] = -self.SPEED/self.param_vals[-6]
            self.final_state_constraints[u7] = 0.0
            # self.final_state_constraints[u8] = -self.SPEED/self.param_vals[-2]
            
        print('-BOUNDS DEFINED')
        
        
        
    def formulate_Opty_problem(self, MAX_INTER = 3000):
        """
        Formulate the problem with Opty.

        Parameters
        ----------
        MAX_INTER : Int, optional
            Maximum number of iteration of the solver. The default is 3000.

        Returns
        -------
        None.

        """
        
        INTERVAL_VALUE = self.INTERVAL_VALUE
        NUM_STATES = self.NUM_STATES
        NUM_INPUTS = self.NUM_INPUTS
        NUM_NODES = self.NUM_NODES

        def obj(free):
            """Cost function definition"""
            x, r, k = parse_free(free, NUM_STATES, NUM_INPUTS, NUM_NODES)
    
            q2 = x[1]
            
            tau_steer, tau_roll = x[-2:]
            
            K = k[:]
            
            # r_dot = np.diff(r)
            
            #Minimize lateral travelled distance
            J1 = INTERVAL_VALUE*((WEIGHT)*(np.sum(q2**2)))
        
            J2 = INTERVAL_VALUE*((1-WEIGHT)*(np.sum((r.flatten())**2)))
            
            # J3 = INTERVAL_VALUE*((1-WEIGHT)*(np.sum((r_dot.flatten())**2)))
            
            J4 = (1-WEIGHT)*np.sum(K**2)
            
            return J1 + J2 + J4
    
    
        def obj_grad(free):
            
            x, r, k = parse_free(free, NUM_STATES, NUM_INPUTS, NUM_NODES)
    
            q2 = x[1]
            
            tau_steer, tau_roll = x[-2:]
            
            K = k[:]
        
            grad = np.zeros_like(free)
            
            grad[1*NUM_NODES:2*NUM_NODES] = 2.0*INTERVAL_VALUE*WEIGHT*q2
            grad[NUM_STATES*NUM_NODES:(NUM_STATES + NUM_INPUTS)*NUM_NODES] = 2.0*(1.0-WEIGHT)*INTERVAL_VALUE*r.flatten()
            
            # grad[(NUM_STATES - 2)*NUM_NODES : (NUM_STATES - 1)*NUM_NODES] = 2.0*(1.0-WEIGHT)*INTERVAL_VALUE*tau_steer
            # grad[(NUM_STATES - 1)*NUM_NODES : (NUM_STATES)*NUM_NODES] = 2.0*(1.0-WEIGHT)*INTERVAL_VALUE*tau_roll

            grad[-len(K):] = 2.0*(1-WEIGHT)*K            

            return grad
        
        motor_noise_magnitude = 0.001
        sensory_noise_magnitude = 0.001
        perturbation_magnitude = 1
        
        dict_sensory_noise = {w_s : np.random.normal(0, sensory_noise_magnitude, (self.NUM_NODES)) for w_s in self.W[:4]}
        dict_motor_noise = {w_m : np.random.normal(0, motor_noise_magnitude, (self.NUM_NODES)) for w_m in self.W[4:]}
        dict_disturbance = {dist : np.random.normal(0, perturbation_magnitude, (self.NUM_NODES)) for dist in self.disturbance}


        self.known_trajectories = dict_sensory_noise | dict_motor_noise | dict_disturbance
        
        
        time_2 = time.time()
        
        instance_constraints = tuple(
                xi.replace(self.t, 0.0) - xi_val for xi, xi_val in self.initial_state_constraints.items()) + tuple(
                xi.replace(self.t, self.DURATION) - xi_val for xi, xi_val in self.final_state_constraints.items())


        for traj in self.known_trajectories.keys():
            self.known_trajectories[traj][0] = 0
            self.known_trajectories[traj][-1] = 0

        state_vars = self.x.col_join(self.r)
        print(state_vars)

        self.problem = Problem(
            obj,
            obj_grad,
            self.eoms,
            state_vars,
            self.NUM_NODES,
            self.INTERVAL_VALUE,
            known_parameter_map = self.p,
            known_trajectory_map = self.known_trajectories,
            instance_constraints = instance_constraints,
            bounds = self.bounds,
            # integration_method='midpoint',
            time_symbol = self.t,
            parallel = True,
            # backend='numpy'
        )
        self.problem.add_option('max_iter' , MAX_INTER)
        
        time_3 = time.time()
        self.prob_def_time = round(time_3 - time_2, 2)
        
        print(f'-OPTY PROBLEM DEFINED - {self.prob_def_time} sec')
        
        
    def solve_Opty_problem(self, initial_guess, visualization_flag = True, N_start=1):
        """
        Run the solver, save and plot the solution found.
        A multi-start feature is implemented. All the results are solved and plot.
        Solving with an initial guess having less nodes is possible, interpolation is implemented.
        Soliving with an initial guess with less models is also possible, sclaing is impkemented.
        Both interpolation and scaling works together.

        Parameters
        ----------
        initial_guess : dict of shape 3
            initial guess given to Opty solver.
            Contains NUM_MODELS and SAMPLING_FREQUENCY to adapat the values
            Value cointains the initial_guess base values.
        visualization_flag : bool, optional
            if True, plots are made. The default is True.
        N_start : int, optional
            Number of start used for the multi-start approach. The default is 1.

        Returns
        -------
        None.

        """
        

        path_results_folder = make_new_results_folder('results/')
        

        self.t_simu = np.linspace(0, self.DURATION, self.NUM_NODES)
        initial_guess_len_needed = ((self.NUM_STATES - len(self.r_dep_list[0]))*self.NUM_MODELS + len(self.r_dep_list[0]) + self.NUM_INPUTS )*self.NUM_NODES + len(self.k)
        
        
        
        # print((self.NUM_STATES - len(self.r_dep_list)))
        
        # print(len(self.r_dep_list) + self.NUM_INPUTS)
        
        print('initial_guess_len_needed', initial_guess_len_needed)

        if self.SAMPLING_FREQUENCY != initial_guess['SAMPLING_FREQUENCY']:#Need to interpolate:
            
            print('- Interpolating initial guess')
            
            initial_guess_value_interp = np.empty((self.NUM_STATES*initial_guess['NUM_MODELS'] + self.NUM_INPUTS)*self.NUM_NODES + len(self.k))
            previous_NUM_NODES = len(initial_guess['value'] - len(self.k)) // (self.NUM_STATES*initial_guess['NUM_MODELS'] + self.NUM_INPUTS) 
            
            initial_guess_value_interp[- len(self.k):] = initial_guess['value'][- len(self.k):]
            
            #We assume NUM_STATES and NUM_INPUTS are the same
            for k in range(self.NUM_STATES*initial_guess['NUM_MODELS'] + self.NUM_INPUTS):
                x_k = initial_guess['value'][k*previous_NUM_NODES:(k + 1)*previous_NUM_NODES]
                t_interp = np.linspace(0, self.DURATION, len(x_k))
        
                f_initial_guess = interp1d(t_interp, x_k, kind='cubic')
                initial_guess_value_interp[k*self.NUM_NODES:(k + 1)*self.NUM_NODES] = f_initial_guess(self.t_simu)
        
            initial_guess['value'] = initial_guess_value_interp
            
            
            
            if self.NUM_MODELS != initial_guess['NUM_MODELS']: #Need to scale
            
                print('- Scaling initial guess')
                
                initial_guess_value_interp_scaled = np.empty(initial_guess_len_needed)*0
                NUM_MODEL_MISSING = self.NUM_MODELS - initial_guess['NUM_MODELS']
                

                
                if NUM_MODEL_MISSING > 0 : #Up scaling
                    
                    len_states_values_ready = len(initial_guess['value']) - self.NUM_NODES*(len(self.r_dep_list[0]) + len(self.r_ind_list[0]) + len(self.k))
                        
                    filling_values = initial_guess['value'][:len_states_values_ready]
                    
                    #Values of states we already have ready
                    initial_guess_value_interp_scaled[:len_states_values_ready] = filling_values
                    initial_guess_value_interp_scaled[- self.NUM_NODES*(len(self.r_dep_list[0]) + len(self.r_ind_list[0]) + len(self.k)):] = initial_guess['value'][len_states_values_ready:]
                     
                    
                    for k in range(NUM_MODEL_MISSING):
          
                        initial_guess_value_interp_scaled[len_states_values_ready + (self.NUM_NODES*(self.NUM_STATES - len(self.r_dep_list[0])))*k:len_states_values_ready + (self.NUM_NODES*(self.NUM_STATES - len(self.r_dep_list[0])))*(k + 1)] = filling_values
                    
                    initial_guess['value'] = initial_guess_value_interp_scaled

                        
                else:
                    raise NameError('Down Scaling not implemented yet')

                    
            
        else : #No need to interplate
        
            if self.NUM_MODELS != initial_guess['NUM_MODELS']: #Need to scale
            
                print('- Scaling initial guess')
                
                initial_guess_value_interp_scaled = np.empty(initial_guess_len_needed)*0
                NUM_MODEL_MISSING = self.NUM_MODELS - initial_guess['NUM_MODELS']
                

                if NUM_MODEL_MISSING > 0 : #Up scaling
                    
                
                    len_states_values_ready = len(initial_guess['value']) - self.NUM_NODES*(len(self.r_ind_list[0]) + len(self.r_dep_list[0]))
                    filling_values = initial_guess['value'][:len_states_values_ready]

                    
                    #Values of states we already have ready
                    initial_guess_value_interp_scaled[:len_states_values_ready] = filling_values
                    initial_guess_value_interp_scaled[- self.NUM_NODES*(len(self.r_ind_list[0]) + len(self.r_dep_list[0])):] = initial_guess['value'][len_states_values_ready:]     
                     
                    for k in range(NUM_MODEL_MISSING):

                        initial_guess_value_interp_scaled[len_states_values_ready + len_states_values_ready*k:len_states_values_ready + len_states_values_ready*(k + 1)] = filling_values
                        
                    
                    initial_guess['value'] = initial_guess_value_interp_scaled
                    
                    print(len(initial_guess_value_interp_scaled))
                        
                else:
                    raise NameError('Down Scaling not implemented yet')
            

        for n_start in range(N_start):

            time_4 = time.time()
            # initial_guess = np.zeros((NUM_STATES_TOT+NUM_INPUTS)*NUM_NODES)
            
            
            # Find the optimal solution.
            self.sol, self.info = self.problem.solve(initial_guess['value'])
            

            # problem.plot_trajectories(sol)
            
            self.k_opt = self.sol[-len(self.k):]
            self.x_opt = self.sol[:-len(self.k)].reshape(-1, self.NUM_NODES)[:self.NUM_STATES_TOT - len(self.r_dep_list[0]), :]
            self.r_dep_opt = self.sol[:-len(self.k)].reshape(-1, self.NUM_NODES)[self.NUM_STATES_TOT - len(self.r_dep_list[0]) : self.NUM_STATES_TOT, :]
            self.r_ind_opt = self.sol[:-len(self.k)].reshape(-1, self.NUM_NODES)[- len(self.r_ind_list[0]):, :]

            time_5 = time.time()
            
            self.solving_time = round(time_5 - time_4, 2)
            
            print(f'- START {n_start+1}/{N_start} SOLVED - {self.solving_time} sec')
            
            print('Optimal Gains:', self.k_opt)

            to_save = {
                'model_type' : self.model_type,
                'n_start' : n_start,
                'NUM_STATES' : self.NUM_STATES,
                'NUM_INPUTS' : self.NUM_INPUTS,
                'NUM_MODELS' : self.NUM_MODELS,
                'WEIGHT' : self.WEIGHT,
                'SPEED' : self.SPEED,
                'DURATION' : self.DURATION,
                'NUM_NODES'  : self.NUM_NODES,
                'INTERVAL_VALUE' : self.INTERVAL_VALUE,
                'known_trajectories' : self.known_trajectories,
                'x' : self.x,
                'r' : self.r,
                'k' : self.k,
                'p' : self.p,
                'bounds' : self.bounds,
                'obj_value' : self.problem.obj_value,
                'info' : self.info,
                'model_generation_time' : self.init_time,
                'prob_def_time' : self.prob_def_time,
                'solving_time' : self.solving_time,
                't_simu' : self.t_simu,
                'k_opt' : self.k_opt,
                'x_opt' : self.x_opt,
                'r_dep_opt' : self.r_dep_opt,
                'r_ind_opt' : self.r_ind_opt}
                
            save_results(to_save, path_results_folder)
            export_results_as_csv(self.t_simu, self.k_opt, self.x_opt, self.r_dep_opt, self.r_ind_opt, self.k, self.x, self.r, n_start, self.model_type, self.known_trajectories, path_results_folder)

            if visualization_flag == True:
              
                self.problem.plot_objective_value()
                self.problem.plot_constraint_violations(self.sol)
                
                
                for model_index in range(self.NUM_MODELS):
                            
    
                    x_opt_model = self.x_opt[model_index*(self.NUM_STATES - len(self.r_dep_list[0])) : (self.NUM_STATES - len(self.r_dep_list[0]))*(model_index + 1), :] #DO NOT contains dep torques
                    # T_opt_model = self.T_opt[model_index*self.NUM_INPUTS:self.NUM_INPUTS*(model_index+1), :]
                    disturbance_model =  self.known_trajectories[list(self.known_trajectories.keys())[model_index]]
                    x_model = self.x[model_index*(self.NUM_STATES - len(self.r_dep_list[0])):(self.NUM_STATES - len(self.r_dep_list[0]))*(model_index + 1)]
                    x_model = x_model + self.x[- len(self.r_dep_list[0]):]
                    r_model = self.r
                    
                    self.x_model = x_model
                    
                    # print(x_opt_model.shape)
                    # print(self.r_opt.shape)
                    # print(disturbance_model)
                    
                    
                    # np.vstack((x_opt_model, self.r_opt, disturbance_model))
                    
                    # print(len(x_opt_model))
                    # print(len(self.r_dep_opt))

                    # print(len(self.r_ind_opt))
                    # print(len(disturbance_model))

                    plot_optimal_solution(self.t_simu, self.x_list, self.r_dep_list, self.r_ind_list, self.disturbance_list, n_start, model_index, np.vstack((x_opt_model, self.r_dep_opt, self.r_ind_opt, disturbance_model)), path_results_folder)
            
                    # x_opt_model_ani = self.x_opt[model_index*self.NUM_STATES:self.NUM_STATES*(model_index + 1), :]
                    
                    if False:
                        animate_solution(self.t_simu, 
                                     x_opt_model, 
                                     np.empty((len(socp_1.r), self.NUM_NODES)), #We don't need to good values for the ani
                                     disturbance_model, 
                                     self.bicycle_list[model_index], 
                                     x_model, 
                                     r_model,
                                     self.p,
                                     path_results_folder + f'animation_{model_index}')
            
      

MAX_INTER = 50000
NUM_MODELS = 1
model_type = 'model_level_1'
WEIGHT = 0.5
SPEED = 2.5  # m/s
DURATION = 3 # s
SAMPLING_FREQUENCY = 25

socp_1 = SOCP_problem(NUM_MODELS, model_type)

socp_1.generate_bounds_and_contstraints(SPEED, SAMPLING_FREQUENCY=5)
# We can manually adjust the bounds here
socp_1.formulate_Opty_problem(MAX_INTER)

# Solving a first time a random initial guess
# initial_guess = np.random.rand((socp_1.NUM_STATES_TOT + socp_1.NUM_INPUTS)*socp_1.NUM_NODES)

initial_guess =  {'NUM_MODELS' : NUM_MODELS,
                  'SAMPLING_FREQUENCY' : 5,
                  'value' : np.zeros((socp_1.NUM_STATES_TOT + socp_1.NUM_INPUTS)*socp_1.NUM_NODES + len(socp_1.k))}

# initial_guess =  {'NUM_MODELS' : NUM_MODELS,
#                   'SAMPLING_FREQUENCY' : SAMPLING_FREQUENCY,
#                   'value' : socp_1.sol}

socp_1.solve_Opty_problem(initial_guess, visualization_flag = False, N_start=1)


initial_guess =  {'NUM_MODELS' : NUM_MODELS,
                  'SAMPLING_FREQUENCY' : 5,
                  'value' : socp_1.sol}

socp_2 = SOCP_problem(1, model_type)
socp_2.generate_bounds_and_contstraints(SPEED, SAMPLING_FREQUENCY = 25)
socp_2.formulate_Opty_problem(MAX_INTER = 5000)
socp_2.solve_Opty_problem(initial_guess, visualization_flag = True, N_start = 1)




# init = np.zeros(3*25*(16+2+1)+8)
# ones = np.ones(3*25)
# init[16*3*25 + 3*25*2 : 16*3*25 + 3*25*3] = ones

initial_guess =  {'NUM_MODELS' : 1,
                  'SAMPLING_FREQUENCY' : 25,
                  'value' : socp_2.sol}

socp_3 = SOCP_problem(2, model_type)
socp_3.generate_bounds_and_contstraints(SPEED, SAMPLING_FREQUENCY = 25)
socp_3.formulate_Opty_problem(MAX_INTER = 5000)
socp_3.solve_Opty_problem(initial_guess, visualization_flag = True, N_start = 1)





