# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 20:03:25 2026

@author: Jules
"""


import matplotlib.pyplot as plt
import numpy as np
import sympy as sm
import sympy.physics.mechanics as me
from opty import Problem
from opty.utils import parse_free
from generate_eom_model_level_0 import generate_model
from utils import plot_optimal_solution, animate_solution, save_results, export_results_as_csv, stats_plot_about_same_model
from utils import make_new_results_folder
import matplotlib.pyplot as plt
import time
from scipy.interpolate import interp1d


class SOCP_problem:
    
    def __init__(self, NUM_MODELS, model_type):
        """
        Initialize the SOCP_problem class that can handle the optimization 
        process using Opty for different model type. The problem is solving for
        optimal control for multiple episodes at the same time. Gaussian noise 
        is introduced in each model.

        Parameters
        ----------
        NUM_MODELS : int
            Nomber of models to optimize at the same time 
            (ie. number of episodes).
        model_type : str
            type of model (i.e. name of model generated by the 'generate_model'
            function).

        Returns
        -------
        None.

        """
        
        
        # Generates N models and compile them
        time_0 = time.time()
        model_names = [f'm{k}' for k in range(NUM_MODELS)]
        
        print(f'PROBLEM INITIALIZED - {NUM_MODELS} models of type "{model_type}":')

        t_list, x_list, r_list, eoms_list, p_list, bicycle_list, disturbance_list = [],[],[],[],[],[],[]

        for model in model_names:
            t_model, x_model, r_model, eoms_model, p_model, bicycle_model, disturbance_model = generate_model(model)
            
            t_list.append(t_model)
            x_list.append(x_model)
            r_list.append(r_model)
            eoms_list.append(eoms_model)
            p_list.append(p_model)
            bicycle_list.append(bicycle_model)
            disturbance_list.append(disturbance_model)

        self.NUM_MODELS = NUM_MODELS
        self.t = t_list[0]
        self.x = x_list[0]
        self.r = r_list[0]
        self.eoms = eoms_list[0]
        self.p = p_list[0]
        self.disturbance = disturbance_list[0]
        self.bicycle_list = bicycle_list
        
        self.x_list = x_list
        self.r_list = r_list
        self.disturbance_list = disturbance_list
        
        if self.NUM_MODELS>1:
            for k in range(1, NUM_MODELS):
                self.x = self.x.col_join(x_list[k])
                self.r = self.r.col_join(r_list[k])
                self.eoms = self.eoms.col_join(eoms_list[k])
                self.disturbance = self.disturbance.col_join(disturbance_list[k])
        



        self.param, self.param_vals = zip(*self.p.items())




        self.NUM_STATES = len(x_list[0])
        self.NUM_INPUTS = len(r_list[0])
        self.NUM_KNOWN_TRAJ = 1
        
        self.NUM_STATES_TOT = NUM_MODELS*self.NUM_STATES
        self.NUM_INPUTS_TOT = NUM_MODELS*self.NUM_INPUTS
        time_1 = time.time()
        
        self.init_time = round(time_1 - time_0, 2)
        
        self.model_type = model_type

        
        print(f'-MODEL(S) INITIALIZED - { self.init_time} sec')
        


    def generate_bounds_and_contstraints(self, SPEED, SAMPLING_FREQUENCY):
        """
        Defines the bounds and the constraints of the optimal problem.
        Values are used by default, but new ones can be defined by over writing
        resulting dictionaries.

        Parameters
        ----------
        SPEED : float
            Longitudinal speed of the bicycle.
        SAMPLING_FREQUENCY : int
            number of nodes per unit of simulated time

        Returns
        -------
        None.

        """
        
        self.bounds = {}
        self.initial_state_constraints = {}
        self.final_state_constraints = {}
        self.SPEED = SPEED
        
        self.WEIGHT = 0.5
        self.DURATION = 3
        self.NUM_NODES = SAMPLING_FREQUENCY*self.DURATION #Au moins 10 Hz
        self.INTERVAL_VALUE = self.DURATION / (self.NUM_NODES - 1)
        
        for model_index in range(self.NUM_MODELS):
            
            
            q1, q2, q3, q4, q5, q6, q7, q8,  = self.x[model_index*self.NUM_STATES:self.NUM_STATES*model_index+self.NUM_STATES//2]
            u1, u2, u3, u4, u5, u6, u7, u8 = self.x[model_index*self.NUM_STATES+self.NUM_STATES//2:model_index*self.NUM_STATES+self.NUM_STATES]
            steer_torque, pedaling_torque = self.r[model_index*self.NUM_INPUTS:self.NUM_INPUTS*(model_index+1)]
        
    
            self.bounds[q1] = (-0.1, self.SPEED*self.DURATION*1.1)
            self.bounds[q2] = (-2, 2) #Si large la vélo est stabilisé mais part sur le coté
            self.bounds[q3] = (-1.0, 1.0)
            self.bounds[q4] = (0, 1.0)
            self.bounds[q5] = (-1, 1)
            self.bounds[q6] = (-100, 0)
            self.bounds[q7] = (-0.7, 0.7)
            self.bounds[q8] = (-100, 0)
            self.bounds[u1] = (self.SPEED*0.95, self.SPEED*1.05) #ok
            self.bounds[u2] = (-5, 5) #ok
            self.bounds[u3] = (-2.0, 2.0)
            self.bounds[u4] = (-4.0, 4.0)
            self.bounds[u5] = (-4.0, 4.0)
            self.bounds[u6] = (-20.0, 0.0)
            self.bounds[u7] = (-4.0, 4.0) #ok
            self.bounds[u8] = (-20.0, 0.0)
            self.bounds[steer_torque] = (-20,20) #ok
            self.bounds[pedaling_torque] = (-30,0)
    
    
    
            self.initial_state_constraints[q1] = 0.0
            self.initial_state_constraints[q2] = 0.0
            self.initial_state_constraints[q3] = 0.0
            self.initial_state_constraints[q4] = 0.0
            self.initial_state_constraints[q5] = 0.39968039870670147 # Super critique
            self.initial_state_constraints[q6] = 0.0
            self.initial_state_constraints[q7] = 0.0
            self.initial_state_constraints[q8] = 0.0
            self.initial_state_constraints[u1] = self.SPEED
            self.initial_state_constraints[u2] = 0.0
            self.initial_state_constraints[u3] = 0.0
            self.initial_state_constraints[u4] = 0.0
            self.initial_state_constraints[u5] = 0.0
            self.initial_state_constraints[u6] = - self.SPEED/self.param_vals[-6]
            self.initial_state_constraints[u7] = 0.0
            self.initial_state_constraints[u8] = - self.SPEED/self.param_vals[-2]
            
            self.initial_state_constraints[steer_torque] = 0
            # self.initial_state_constraints[pedaling_torque] = 0
        
    
    
            # self.final_state_constraints[q1] = self.SPEED*self.DURATION
            # self.final_state_constraints[q2] = 0.0
            # self.final_state_constraints[q3] = 0.0
            # self.final_state_constraints[q4] = 0.0
            # self.final_state_constraints[q5] = -0.314
            # self.final_state_constraints[q6] = 0.0
            # self.final_state_constraints[q7] = 0.0
            # self.final_state_constraints[q8] = 0.0
            # self.final_state_constraints[u1] = self.SPEED
            # self.final_state_constraints[u2] = 0.0
            self.final_state_constraints[u3] = 0.0
            self.final_state_constraints[u4] = 0.0
            # self.final_state_constraints[u5] = 0.0
            # self.final_state_constraints[u6] = -self.SPEED/self.param_vals[-6]
            self.final_state_constraints[u7] = 0.0
            # self.final_state_constraints[u8] = -self.SPEED/self.param_vals[-2]
        print('-BOUNDS DEFINED')
        
        
        
    def formulate_Opty_problem(self, MAX_INTER = 3000):
        """
        Formulate the problem with Opty.

        Parameters
        ----------
        MAX_INTER : Int, optional
            Maximum number of iteration of the solver. The default is 3000.

        Returns
        -------
        None.

        """
        
        INTERVAL_VALUE = self.INTERVAL_VALUE
        NUM_STATES = self.NUM_STATES
        NUM_INPUTS = self.NUM_INPUTS
        NUM_NODES = self.NUM_NODES

        def obj(free):
            """Cost function definition"""
            x, r, _ = parse_free(free, NUM_STATES, NUM_INPUTS, NUM_NODES)
    
            q2 = x[1]
            
            #Minimize latral travelled distance
            J2 = INTERVAL_VALUE*((WEIGHT)*(np.sum(q2)**2))
        
            J3 = INTERVAL_VALUE*((1-WEIGHT)*(np.sum((r.flatten())**2)))
            
            return J2+J3
    
    
        def obj_grad(free):
            x, r, _ = parse_free(free, NUM_STATES, NUM_INPUTS, NUM_NODES)
    
            q2 = x[1]
        
            grad = np.zeros_like(free)
            
            grad[1*NUM_NODES:2*NUM_NODES] = 2.0*INTERVAL_VALUE*WEIGHT*q2
            grad[NUM_STATES*NUM_NODES:(NUM_STATES + NUM_INPUTS)*NUM_NODES] = 2.0*(1.0-WEIGHT)*INTERVAL_VALUE*r.flatten()
            
            return grad
        
        motor_noise_magnitude = 2.5
        
        time_2 = time.time()
        
        instance_constraints = tuple(
                xi.replace(self.t, 0.0) - xi_val for xi, xi_val in self.initial_state_constraints.items()) + tuple(
                xi.replace(self.t, self.DURATION) - xi_val for xi, xi_val in self.final_state_constraints.items())

        self.known_trajectories = {dist : np.random.normal(0, motor_noise_magnitude, self.NUM_NODES) for dist in self.disturbance}

        state_vars = self.x.col_join(self.r)

        self.problem = Problem(
            obj,
            obj_grad,
            self.eoms,
            state_vars,
            self.NUM_NODES,
            self.INTERVAL_VALUE,
            known_parameter_map = self.p,
            known_trajectory_map = self.known_trajectories,
            instance_constraints= instance_constraints,
            bounds= self.bounds,
            # integration_method='midpoint',
            time_symbol= self.t,
            parallel= True,
            # backend='numpy'
        )
        self.problem.add_option('max_iter' , MAX_INTER)
        
        time_3 = time.time()
        self.prob_def_time = round(time_3 - time_2, 2)
        
        print(f'-OPTY PROBLEM DEFINED - {self.prob_def_time} sec')
        
        
    def solve_Opty_problem(self, initial_guess, visualization_flag = True, N_start=1):
        """
        Run the solver, save and plot the solution found.
        A multi-start feature is implemented. All the results are solved and plot.

        Parameters
        ----------
        initial_guess : np.array ((NUM_STATES_TOT+NUM_INPUTS_TOT)*NUM_NODES,)
            initial guess given to Opty solver.
        visualization_flag : bool, optional
            if True, plots are made. The default is True.
        N_start : int, optional
            Number of start used for the multi-start approach. The default is 1.

        Returns
        -------
        None.

        """
        

        path_results_folder = make_new_results_folder('results/')
        self.t_simu = np.linspace(0, self.DURATION, self.NUM_NODES)
        initial_guess_len = (self.NUM_STATES_TOT+self.NUM_INPUTS_TOT)*self.NUM_NODES
        
        
        if len(initial_guess) != initial_guess_len :
            
            new_initial_guess = np.empty(initial_guess_len)
            previous_NUM_NODES = len(initial_guess) // (self.NUM_STATES_TOT+self.NUM_INPUTS_TOT)
            
            for k in range(self.NUM_STATES_TOT+self.NUM_INPUTS_TOT):
                x_k = initial_guess[k*previous_NUM_NODES:(k+1)*previous_NUM_NODES]
                t_interp = np.linspace(0, self.DURATION, len(x_k))

                f_initial_guess = interp1d(t_interp, x_k, kind='cubic')
                new_initial_guess[k*self.NUM_NODES:(k+1)*self.NUM_NODES] = f_initial_guess(self.t_simu)

            initial_guess = new_initial_guess

        for n_start in range(N_start):

            time_4 = time.time()
            # initial_guess = np.zeros((NUM_STATES_TOT+NUM_INPUTS_TOT)*NUM_NODES)
            
            
            # Find the optimal solution.
            self.sol, self.info = self.problem.solve(initial_guess)
            

            # problem.plot_trajectories(sol)
            

            self.x_opt, self.T_opt = self.sol.reshape(-1, self.NUM_NODES)[:-self.NUM_INPUTS_TOT,:], self.sol.reshape(-1, self.NUM_NODES)[-self.NUM_INPUTS_TOT:,:]
            
            time_5 = time.time()
            
            self.solving_time = round(time_5 - time_4, 2)
            
            print(f'- START {n_start+1}/{N_start} SOLVED - {self.solving_time} sec')

            to_save = {
                'model_type' : self.model_type,
                'n_start' : n_start,
                'NUM_STATES' : self.NUM_STATES,
                'NUM_INPUTS' : self.NUM_INPUTS,
                'NUM_MODELS' : self.NUM_MODELS,
                'WEIGHT' : self.WEIGHT,
                'SPEED' : self.SPEED,
                'DURATION' : self.DURATION,
                'NUM_NODES'  : self.NUM_NODES,
                'INTERVAL_VALUE' : self.INTERVAL_VALUE,
                'known_trajectories' : self.known_trajectories,
                'x' : self.x,
                'r' : self.r,
                'p' : self.p,
                'bounds' : self.bounds,
                'obj_value' : self.problem.obj_value,
                'info' : self.info,
                'model_generation_time' : self.init_time,
                'prob_def_time' : self.prob_def_time,
                'solving_time' : self.solving_time,
                't_simu' : self.t_simu,
                'x_opt' : self.x_opt,
                'T_opt' : self.T_opt}
                
            save_results(to_save, path_results_folder)
            export_results_as_csv(self.t_simu, self.x_opt, self.T_opt, self.x, self.r, n_start, self.model_type, self.known_trajectories, path_results_folder)

            if visualization_flag == True:
              
                self.problem.plot_objective_value()
                self.problem.plot_constraint_violations(self.sol)
                
                
                for model_index in range(self.NUM_MODELS):
                            
                            
                    x_opt_model = self.x_opt[model_index*self.NUM_STATES:self.NUM_STATES*(model_index+1), :]
                    T_opt_model = self.T_opt[model_index*self.NUM_INPUTS:self.NUM_INPUTS*(model_index+1), :]
                    disturbance_model =  self.known_trajectories[list(self.known_trajectories.keys())[model_index]]
                    x_model = self.x[model_index*self.NUM_STATES:self.NUM_STATES*(model_index+1)]
                    r_model = self.r[model_index*self.NUM_INPUTS]
                    
                    plot_optimal_solution(self.t_simu, self.x_list, self.r_list, self.disturbance_list, n_start, model_index, np.vstack((x_opt_model, T_opt_model, disturbance_model)), path_results_folder)
            
                    animate_solution(self.t_simu, 
                                 x_opt_model, 
                                 T_opt_model, 
                                 disturbance_model, 
                                 self.bicycle_list[model_index], 
                                 x_model, 
                                 r_model,
                                 self.p,
                                 path_results_folder + f'animation_{model_index}')
        
      

MAX_INTER = 3000
NUM_MODELS = 1
model_type = 'model_level_0'
WEIGHT = 0.5
SPEED = 2.5  # m/s
DURATION = 3 # s
SAMPLING_FREQUENCY = 25

socp_1 = SOCP_problem(NUM_MODELS, model_type)

socp_1.generate_bounds_and_contstraints(SPEED, SAMPLING_FREQUENCY=25)
# We can manually adjust the bounds here
socp_1.formulate_Opty_problem()

# Solving a first time a random initial guess
initial_guess = np.random.rand((socp_1.NUM_STATES_TOT + socp_1.NUM_INPUTS_TOT)*socp_1.NUM_NODES)
socp_1.solve_Opty_problem(initial_guess, visualization_flag = False, N_start=1)

initial_guess = socp_1.sol #Using previous result as an intial guess
socp_1.generate_bounds_and_contstraints(SPEED, SAMPLING_FREQUENCY=100)
socp_1.formulate_Opty_problem()
socp_1.solve_Opty_problem(initial_guess, visualization_flag = True, N_start=2)


